
<h2>CSV 2 POST Disclaimer, Terms &amp; Conditions</h2>
<p>Please read and agree to the following conditions in order to use this plugin...</p>
<ol>
  <li>CSV 2 POST requires the creation of a new campaign before it will take any effect. The campaign settings and the CSV file you upload will determine the outcome.&nbsp;If the outcome based on your entered campaign settings is not as you&nbsp;expected, WebTechGlobal is not responsible/liable. When a campaign is begun you may observe and test&nbsp;CSV 2 POST's effects before allowing it to continue.&nbsp;Any issues created from mass post creation based on incorrect settings is not the responsibility or liability of WebTechGlobal.</li>
  <li>You are responsible for the CSV file data that you use and any data in your CSV file is rendered for public use when you upload it via CSV 2 POST. You agree to only use CSV files that only contain public data. Such data is allowed to be in the hands of the public and displayed online.</li>
  <li>This plugin allows you to assign specific parts of that data to specific data requirements in WordPress posts. If you have data in your CSV file that should not be public and this data is used through incorrect settings or due to any fault&nbsp;in the plugin itself, WebTechGlobal is not liable. If you accept term (2) then you agree to only use files that contain public data&nbsp;only. Liability does apply to WebTechGlobal if the plugin has bugs as a plugins cannot be tested in every possible envronment or under conditions that users may operate it.</li>
  <li>The CSV 2 POST plugin has been created as a tool that will bring positive results to your blog in terms of content.&nbsp;In the event that adding mass amounts of content to your blog causes negative effects in any way; WebTechGlobal is not liable.</li>
  <li>This plugin like most plugins have been developed and provided free of charge. No financial compensation will be provided under any circumstances .</li>
  <li>CSV 2 POST will create WordPress &quot;Posts&quot; and not &quot;Pages&quot;. Creating pages is not an ability built into this plugin and it probably will not be at any time in future. If you use the plugin under the perception that it will create Pages on your blog rather than Posts, WebTechGlobal is not reponsible/liable for the outcome.</li>
</ol>